name: Test build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build
        run: |
          git clone https://github.com/embroidermodder/libembroidery
          cd libembroidery
          bash build.sh --github
