name: Mac OS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build
        run: |
          git clone https://github.com/embroidermodder/libembroidery
          cd libembroidery
          bash build.sh --github
